name: GreasyFork Release

on:
  push:
    tags:
      - "client=v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Release
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/checkout@v4
      - name: Build
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/client=}" >> $GITHUB_ENV
          cd packages/client
          pnpm install
          pnpm run check && pnpm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "GreasyFork script release: ${{ env.RELEASE_VERSION }}"
          body_path: ./packages/client/release-path.txt
          generate_release_notes: true
          files: |
            ./packages/client/dist/s1-reaction.user.js
